server:
  port: 8888

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/NotesData?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: elasticsearch 
  rabbitmq:
    host: localhost
    virtual-host: admin
    port: 15672      

logging:
  level:
    org: ERROR
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/NotesData-dev?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin-dev
  jpa:
    hibernate:
      ddl-auto: update
    properties: 
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect